import React from 'react';
import {
    IoHome, IoSchool, IoBriefcase, IoCart, IoFitness, IoGameController,
    IoMusicalNotes, IoBook, IoCode, IoAirplane, IoRestaurant, IoBuild,
    IoConstruct, IoStar, IoHeart, IoFlag, IoAlarm, IoCalendar, IoCamera,
    IoChatbubble, IoCloud, IoCompass, IoCut, IoDesktop, IoDiamond,
    IoDocument, IoEarth, IoEye, IoFilm, IoFlame, IoFlash, IoFlower,
    IoFolder, IoGift, IoGlobe, IoHammer, IoHappy, IoHeadset, IoImage, IoBulb,
    IoKey, IoLaptop, IoLeaf, IoLibrary, IoLink, IoLocation, IoLockClosed,
    IoMail, IoMap, IoMedal, IoMegaphone, IoMic, IoMoon, IoNotifications,
    IoPaperPlane, IoPencil, IoPeople, IoPerson, IoPhonePortrait, IoPieChart,
    IoPin, IoPlanet, IoPlay, IoPower, IoPrint, IoPulse, IoRadio, IoRainy,
    IoRecording, IoReload, IoRestaurantOutline, IoRocket, IoRose, IoSave,
    IoScan, IoSearch, IoSend, IoSettings, IoShare, IoShield, IoShirt,
    IoShuffle, IoSnow, IoSpeedometer, IoSquare, IoStatsChart, IoStopwatch,
    IoSunny, IoSync, IoTabletLandscape, IoTerminal, IoText, IoThermometer,
    IoThumbsUp, IoTime, IoTimer, IoTrash, IoTrophy, IoUmbrella, IoVideocam,
    IoVolumeHigh, IoWallet, IoWarning, IoWatch, IoWater, IoWifi, IoWine
} from 'react-icons/io5';

export const ICON_MAP: Record<string, React.ComponentType<{ size?: number, color?: string, style?: React.CSSProperties }>> = {
    'home': IoHome,
    'school': IoSchool,
    'work': IoBriefcase,
    'cart': IoCart,
    'fitness': IoFitness,
    'game': IoGameController,
    'music': IoMusicalNotes,
    'book': IoBook,
    'code': IoCode,
    'travel': IoAirplane,
    'food': IoRestaurant,
    'build': IoBuild,
    'construct': IoConstruct,
    'star': IoStar,
    'heart': IoHeart,
    'flag': IoFlag,
    'alarm': IoAlarm,
    'calendar': IoCalendar,
    'camera': IoCamera,
    'chat': IoChatbubble,
    'cloud': IoCloud,
    'compass': IoCompass,
    'desktop': IoDesktop,
    'diamond': IoDiamond,
    'document': IoDocument,
    'earth': IoEarth,
    'eye': IoEye,
    'film': IoFilm,
    'fire': IoFlame,
    'flash': IoFlash,
    'flower': IoFlower,
    'folder': IoFolder,
    'gift': IoGift,
    'globe': IoGlobe,
    'idea': IoBulb, // IoBulb not in import list, checking io5 list
    // 'bulb': IoBulb, // skipped
    'happy': IoHappy,
    'image': IoImage,
    'key': IoKey,
    'laptop': IoLaptop,
    'leaf': IoLeaf,
    'link': IoLink,
    'location': IoLocation,
    'lock': IoLockClosed,
    'mail': IoMail,
    'map': IoMap,
    'medal': IoMedal,
    'mic': IoMic,
    'moon': IoMoon,
    'notification': IoNotifications,
    'pencil': IoPencil,
    'people': IoPeople,
    'person': IoPerson,
    'phone': IoPhonePortrait,
    'pin': IoPin,
    'planet': IoPlanet,
    'play': IoPlay,
    'power': IoPower,
    'rocket': IoRocket,
    'save': IoSave,
    'search': IoSearch,
    'send': IoSend,
    'settings': IoSettings,
    'share': IoShare,
    'shield': IoShield,
    'stats': IoStatsChart,
    'sun': IoSunny,
    'sync': IoSync,
    'terminal': IoTerminal,
    'text': IoText,
    'time': IoTime,
    'trash': IoTrash,
    'trophy': IoTrophy,
    'video': IoVideocam,
    'volume': IoVolumeHigh,
    'wallet': IoWallet,
    'warning': IoWarning,
    'watch': IoWatch,
    'water': IoWater,
    'wifi': IoWifi,
};

// Removed IoBulb as it wasn't in the import list and I don't want to guess valid exports if they fail
// I'll stick to the imported ones.

export const PREDEFINED_ICONS = Object.keys(ICON_MAP);

export const getIconComponent = (iconName: string) => {
    return ICON_MAP[iconName] || null;
};
