package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestFindSkipsVendorAndGitIgnoredDirs(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "go.mod"), `module example.com/root

require (
	example.com/app v0.0.0
	example.com/service v0.0.0
)
`)
	mustWrite(t, filepath.Join(dir, "app", "go.mod"), `module example.com/app

require example.com/service v0.0.0
`)
	mustWrite(t, filepath.Join(dir, "nested", "service", "go.mod"), "module example.com/service\n")
	mustWrite(t, filepath.Join(dir, "template", "go.mod"), "module example.com/{{.Name}}\n\ngo {{.GoVersion}}\n")
	mustWrite(t, filepath.Join(dir, "vendor", "ignored", "go.mod"), "module example.com/vendor\n")
	mustWrite(t, filepath.Join(dir, "ignored", "go.mod"), "module example.com/ignored\n")
	mustWrite(t, filepath.Join(dir, "nested-ignore", ".gitignore"), ".xgo/gen/\n")
	mustWrite(t, filepath.Join(dir, "nested-ignore", ".xgo", "gen", "go.mod"), "module example.com/xgo\n")
	mustWrite(t, filepath.Join(dir, ".gitignore"), "ignored/\n")

	mustRunGit(t, dir, "init")

	modules, err := Find(dir)
	if err != nil {
		t.Fatal(err)
	}

	got := moduleSummaries(modules)
	want := []moduleSummary{
		{Dir: ".", Path: "example.com/root", Depends: []string{"app", "nested/service"}},
		{Dir: "app", Path: "example.com/app", Depends: []string{"nested/service"}},
		{Dir: "nested/service", Path: "example.com/service"},
		{Dir: "template", Path: "example.com/{{.Name}}"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("modules mismatch\nwant: %#v\n got: %#v", want, got)
	}
}

func TestRender(t *testing.T) {
	var buf bytes.Buffer
	err := Render(&buf, []Module{
		{Dir: ".", Path: "example.com/root", Depends: []string{"app", "nested/service"}},
		{Dir: "app", Path: "example.com/app", Depends: []string{"nested/service"}},
		{Dir: "nested/service", Path: "example.com/service"},
	})
	if err != nil {
		t.Fatal(err)
	}

	want := strings.TrimLeft(`
.
├── app
│   └── go.mod
│       └── (depends on) nested/service/go.mod
├── go.mod
│   ├── (depends on) app/go.mod
│   └── (depends on) nested/service/go.mod
└── nested
    └── service
        └── go.mod
`, "\n")
	if buf.String() != want {
		t.Fatalf("tree mismatch\nwant:\n%s\ngot:\n%s", want, buf.String())
	}
}

func TestUpdateLocalDepsAndRender(t *testing.T) {
	dir, origin := setupLocalDepsRepo(t)

	var buf bytes.Buffer
	if err := UpdateLocalDepsAndRender(&buf, dir, false); err != nil {
		t.Fatal(err)
	}

	rootGoMod := mustRead(t, filepath.Join(dir, "go.mod"))
	for _, want := range []string{
		"example.com/root.git/cli v0.0.1",
		"example.com/root.git/types v0.0.1",
	} {
		if !strings.Contains(rootGoMod, want) {
			t.Fatalf("root go.mod missing %q:\n%s", want, rootGoMod)
		}
	}
	if strings.Contains(rootGoMod, "replace example.com/root.git/") {
		t.Fatalf("root go.mod still has local replace:\n%s", rootGoMod)
	}
	if _, err := os.Stat(filepath.Join(dir, "go.sum")); err != nil {
		t.Fatalf("root go.sum was not generated by go mod tidy: %v", err)
	}

	cliGoMod := mustRead(t, filepath.Join(dir, "cli", "go.mod"))
	if !strings.Contains(cliGoMod, "example.com/root.git/types v0.0.1") {
		t.Fatalf("cli go.mod was not updated:\n%s", cliGoMod)
	}
	if strings.Contains(cliGoMod, "replace example.com/root.git/types") {
		t.Fatalf("cli go.mod still has local replace:\n%s", cliGoMod)
	}
	if _, err := os.Stat(filepath.Join(dir, "cli", "go.sum")); err != nil {
		t.Fatalf("cli go.sum was not generated by go mod tidy: %v", err)
	}

	for _, tag := range []string{"types/v0.0.1", "cli/v0.0.1", "v0.0.1"} {
		mustRunGit(t, origin, "rev-parse", "--verify", "refs/tags/"+tag)
		if !strings.Contains(buf.String(), "new tag: "+tag) {
			t.Fatalf("rendered tree missing annotation for %s:\n%s", tag, buf.String())
		}
	}
	if status := mustRunGitOutput(t, dir, "status", "--short"); status != "" {
		t.Fatalf("update left uncommitted changes:\n%s", status)
	}
	if !strings.Contains(buf.String(), "updated: types/go.mod v0.0.0 -> v0.0.1, replace removed") {
		t.Fatalf("rendered tree missing cli dependency annotation:\n%s", buf.String())
	}
	if !strings.Contains(buf.String(), "updated: cli/go.mod v0.0.0 -> v0.0.1, replace removed") {
		t.Fatalf("rendered tree missing root dependency annotation:\n%s", buf.String())
	}
}

func TestUpdateLocalDepsAndRenderDryRun(t *testing.T) {
	dir, origin := setupLocalDepsRepo(t)

	rootGoModBefore := mustRead(t, filepath.Join(dir, "go.mod"))
	cliGoModBefore := mustRead(t, filepath.Join(dir, "cli", "go.mod"))
	headBefore := mustRunGitOutput(t, dir, "rev-parse", "HEAD")

	var buf bytes.Buffer
	if err := UpdateLocalDepsAndRender(&buf, dir, true); err != nil {
		t.Fatal(err)
	}

	if rootGoMod := mustRead(t, filepath.Join(dir, "go.mod")); rootGoMod != rootGoModBefore {
		t.Fatalf("dry-run changed root go.mod\nbefore:\n%s\nafter:\n%s", rootGoModBefore, rootGoMod)
	}
	if cliGoMod := mustRead(t, filepath.Join(dir, "cli", "go.mod")); cliGoMod != cliGoModBefore {
		t.Fatalf("dry-run changed cli go.mod\nbefore:\n%s\nafter:\n%s", cliGoModBefore, cliGoMod)
	}
	if headAfter := mustRunGitOutput(t, dir, "rev-parse", "HEAD"); headAfter != headBefore {
		t.Fatalf("dry-run changed HEAD: before %s after %s", headBefore, headAfter)
	}
	if status := mustRunGitOutput(t, dir, "status", "--short"); status != "" {
		t.Fatalf("dry-run changed git status:\n%s", status)
	}
	if tags := mustRunGitOutput(t, dir, "tag", "-l"); tags != "" {
		t.Fatalf("dry-run created local tags:\n%s", tags)
	}
	if tags := mustRunGitOutput(t, origin, "tag", "-l"); tags != "" {
		t.Fatalf("dry-run pushed tags:\n%s", tags)
	}

	for _, want := range []string{
		"new tag: types/v0.0.1",
		"updated: types/go.mod v0.0.0 -> v0.0.1, replace removed",
		"new tag: cli/v0.0.1",
		"updated: cli/go.mod v0.0.0 -> v0.0.1, replace removed",
		"new tag: v0.0.1",
	} {
		if !strings.Contains(buf.String(), want) {
			t.Fatalf("dry-run output missing %q:\n%s", want, buf.String())
		}
	}
}

func setupLocalDepsRepo(t *testing.T) (string, string) {
	t.Helper()
	dir := t.TempDir()
	origin := filepath.Join(t.TempDir(), "origin.git")

	mustRunGit(t, dir, "init")
	mustRunGit(t, dir, "config", "user.email", "test@example.com")
	mustRunGit(t, dir, "config", "user.name", "Test User")
	if err := os.MkdirAll(origin, 0755); err != nil {
		t.Fatal(err)
	}
	mustRunGit(t, origin, "init", "--bare")
	mustRunGit(t, dir, "remote", "add", "origin", origin)
	configGoFetchFromOrigin(t, origin)

	mustWrite(t, filepath.Join(dir, "go.mod"), `module example.com/root.git
go 1.23.0

require (
	example.com/root.git/cli v0.0.0
	example.com/root.git/types v0.0.0
)

replace example.com/root.git/cli => ./cli

replace example.com/root.git/types => ./types
`)
	mustWrite(t, filepath.Join(dir, "root.go"), `package root

import (
	_ "example.com/root.git/cli"
	_ "example.com/root.git/types"
)
`)
	mustWrite(t, filepath.Join(dir, "types", "go.mod"), `module example.com/root.git/types
go 1.23.0
`)
	mustWrite(t, filepath.Join(dir, "types", "types.go"), "package types\n")
	mustWrite(t, filepath.Join(dir, "cli", "go.mod"), `module example.com/root.git/cli
go 1.23.0

require example.com/root.git/types v0.0.0

replace example.com/root.git/types => ../types
`)
	mustWrite(t, filepath.Join(dir, "cli", "cli.go"), `package cli

import _ "example.com/root.git/types"
`)
	mustRunGit(t, dir, "add", ".")
	mustRunGit(t, dir, "commit", "-m", "initial")
	return dir, origin
}

func configGoFetchFromOrigin(t *testing.T, origin string) {
	t.Helper()
	gitConfig := filepath.Join(t.TempDir(), "gitconfig")
	originURL := "file://" + filepath.ToSlash(origin)
	mustWrite(t, gitConfig, `[url "`+originURL+`"]
	insteadOf = https://example.com/root.git
	insteadOf = http://example.com/root.git
	insteadOf = git://example.com/root.git
	insteadOf = ssh://example.com/root.git
	insteadOf = git+ssh://example.com/root.git
	insteadOf = https://example.com/root
	insteadOf = http://example.com/root
	insteadOf = git://example.com/root
	insteadOf = ssh://example.com/root
	insteadOf = git+ssh://example.com/root
`)
	t.Setenv("GIT_CONFIG_GLOBAL", gitConfig)
	t.Setenv("GIT_ALLOW_PROTOCOL", "file:https:http:git:ssh")
	t.Setenv("GOPRIVATE", "example.com")
	t.Setenv("GONOSUMDB", "example.com")
	t.Setenv("GOPROXY", "direct")
	t.Setenv("GOINSECURE", "example.com")
}

type moduleSummary struct {
	Dir     string
	Path    string
	Depends []string
}

func moduleSummaries(modules []Module) []moduleSummary {
	summaries := make([]moduleSummary, 0, len(modules))
	for _, module := range modules {
		summaries = append(summaries, moduleSummary{
			Dir:     module.Dir,
			Path:    module.Path,
			Depends: module.Depends,
		})
	}
	return summaries
}

func mustWrite(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func mustRunGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
}

func mustRunGitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
	return strings.TrimSpace(string(output))
}
