import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import { useState } from 'react';
import { ConfigProvider, Layout, Card, Button, Statistic, Space, Typography } from 'antd';
import { BranchesOutlined } from '@ant-design/icons';
import { ExternalDemo } from '@external_src/demo-external/frontend/src/ExternalDemo';
__APP_GEN_IMPORT__
import { getRoutePrefix } from './routePrefix';
import './App.css';

const routePrefix = getRoutePrefix();

const linkStyle = { color: 'rgba(255, 255, 255, 0.85)' };

function Home() {
    const [count, setCount] = useState(0);

    return (
        <Card style={{ maxWidth: 560, margin: '40px auto' }}>
            <Space direction="vertical" size="large" style={{ width: '100%' }}>
                <Typography.Title level={3} style={{ margin: 0 }}>
                    Welcome to Kool Go-React
                </Typography.Title>
                <Typography.Text type="secondary">
                    Edit <code>src/App.tsx</code> and save to test HMR. UI components come from Ant
                    Design.
                </Typography.Text>
                <Card>
                    <Space size="large">
                        <Statistic title="count" value={count} />
                        <Button type="primary" onClick={() => setCount((count) => count + 1)}>
                            increment
                        </Button>
                    </Space>
                </Card>
                <Link to="/about">Go to About Page</Link>
            </Space>
        </Card>
    );
}

function About() {
    return (
        <Card style={{ maxWidth: 560, margin: '40px auto' }}>
            <Space direction="vertical" size="middle">
                <Typography.Title level={3} style={{ margin: 0 }}>
                    About
                </Typography.Title>
                <Typography.Text type="secondary">
                    This app was generated by <code>kool create</code> with Ant Design preconfigured
                    via <code>ConfigProvider</code>.
                </Typography.Text>
                <Link to="/">Back to Home</Link>
            </Space>
        </Card>
    );
}

function App() {
    return (
        <ConfigProvider theme={{ token: { colorPrimary: '#287c70' } }}>
            <Router basename={routePrefix || undefined}>
                <Layout style={{ minHeight: '100vh' }}>
                    <Layout.Header style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
                        <BranchesOutlined style={{ color: '#fff', fontSize: 18 }} />
                        <nav style={{ display: 'flex', gap: 20 }}>
                            <Link to="/" style={linkStyle}>Home</Link>
                            <Link to="/about" style={linkStyle}>About</Link>
                            <Link to="/external" style={linkStyle}>External Source</Link>
                            __APP_GEN_LINK__
                        </nav>
                    </Layout.Header>
                    <Layout.Content style={{ padding: 24 }}>
                        <Routes>
                            <Route path="/" element={<Home />} />
                            <Route path="/about" element={<About />} />
                            <Route path="/external" element={<ExternalDemo />} />
                            __APP_GEN_ROUTE__
                        </Routes>
                    </Layout.Content>
                </Layout>
            </Router>
        </ConfigProvider>
    );
}

export default App;
